Traceback (most recent call last):
  File "fuzz.py", line 8, in <module>
    with aifc.open(sys.argv[1]) as fd:
  File "aifc.py", line 917, in open
    return Aifc_read(f)
  File "aifc.py", line 352, in __init__
    self.initfp(file_object)
  File "aifc.py", line 334, in initfp
    self._read_comm_chunk(chunk)
  File "aifc.py", line 492, in _read_comm_chunk
    self._compname = _read_string(chunk)
  File "aifc.py", line 173, in _read_string
    length = ord(file.read(1))
TypeError
